<?php

namespace Em\EmliczaczBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends EntityRepository
{
    public function fetchActiveTypes()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT t FROM EmEmliczaczBundle:Type t WHERE t.active = 1 ORDER BY t.id ASC')
                ->getResult();
    }
}
